easy_admin:
  site_name: "Roots"
  entities:
    FaitNotable:
      class: App\Entity\FaitNotable
    Matricule:
      class: App\Entity\Matricule
    Personne:
      class: App\Entity\Personne
    User:
      class: App\Entity\User